-- Initial schema for Agunnaya Labs Studio.
-- Mirrors lib/db/src/schema/index.ts. Safe to run repeatedly.

-- better-auth: users
CREATE TABLE IF NOT EXISTS "user" (
  "id" text PRIMARY KEY,
  "name" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "email_verified" boolean NOT NULL DEFAULT false,
  "image" text,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "wallet_address" text,
  "agl_tier" text DEFAULT 'free',
  "agl_credits" integer DEFAULT 30,
  "subscription_expires_at" timestamp
);

-- better-auth: sessions
CREATE TABLE IF NOT EXISTS "session" (
  "id" text PRIMARY KEY,
  "expires_at" timestamp NOT NULL,
  "token" text NOT NULL UNIQUE,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "ip_address" text,
  "user_agent" text,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

-- better-auth: accounts (credential + oauth)
CREATE TABLE IF NOT EXISTS "account" (
  "id" text PRIMARY KEY,
  "account_id" text NOT NULL,
  "provider_id" text NOT NULL,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "access_token" text,
  "refresh_token" text,
  "id_token" text,
  "access_token_expires_at" timestamp,
  "refresh_token_expires_at" timestamp,
  "scope" text,
  "password" text,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

-- better-auth: verification tokens
CREATE TABLE IF NOT EXISTS "verification" (
  "id" text PRIMARY KEY,
  "identifier" text NOT NULL,
  "value" text NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

-- App: saved Solidity projects
CREATE TABLE IF NOT EXISTS "solidity_projects" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "code" text NOT NULL,
  "description" text,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

-- App: contract deployments
CREATE TABLE IF NOT EXISTS "deployments" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "project_id" integer REFERENCES "solidity_projects"("id") ON DELETE CASCADE,
  "chain_id" integer NOT NULL,
  "contract_name" text,
  "contract_address" text,
  "tx_hash" text,
  "status" text NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- App: AGL token payments (top-ups and subscriptions)
CREATE TABLE IF NOT EXISTS "agl_transactions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "tx_hash" text NOT NULL UNIQUE,
  "type" text NOT NULL,
  "agl_amount" text NOT NULL,
  "credits_added" integer DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- App: AI agent usage log (powers dashboard stats)
CREATE TABLE IF NOT EXISTS "agent_interactions" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "agent_id" text NOT NULL,
  "project_id" integer REFERENCES "solidity_projects"("id") ON DELETE SET NULL,
  "credits_spent" integer NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "session" ("user_id");
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "account" ("user_id");
CREATE INDEX IF NOT EXISTS "solidity_projects_user_id_idx" ON "solidity_projects" ("user_id");
CREATE INDEX IF NOT EXISTS "deployments_user_id_idx" ON "deployments" ("user_id");
CREATE INDEX IF NOT EXISTS "agl_transactions_user_id_idx" ON "agl_transactions" ("user_id");
CREATE INDEX IF NOT EXISTS "agent_interactions_user_id_idx" ON "agent_interactions" ("user_id");

-- Columns added after the first release are applied defensively so this file
-- stays runnable against databases created from an earlier version.
ALTER TABLE "deployments" ADD COLUMN IF NOT EXISTS "contract_name" text;
